/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package IntegerSort;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class SortTest {

    private void assertSorted(List<Integer> unsorted, List<Integer> sorted) {
        assertThat(sort(unsorted), is(sorted));
    }

    private List<Integer> intList(Integer... ints) {
        return Arrays.asList(ints);
    }

    @Test
    public void sortings() throws Exception {
        assertSorted(intList(), intList());
        assertSorted(intList(1), intList(1));
        assertSorted(intList(2, 1), intList(1, 2));
        assertSorted(intList(1, 3, 2), intList(1, 2, 3));
    }

    private List<Integer> sort(List<Integer> list) {
        if (list.size() > 1) {
            if (list.get(0) > list.get(1)) {
                Integer temp = list.get(0);
                list.set(0, list.get(1));
                list.set(1, temp);
            }

            if (list.get(1) > list.get(2)) {
                Integer temp = list.get(1);
                list.set(1, list.get(2));
                list.set(2, temp);
            }
        }

        return list;
    }
}
